version: '3.8'

volumes:
  static_backend_value:
  media_data:
  postgresql_data:

services:
  db:
    image: postgres:13.10
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  backend:
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    image: ganetzckayaliza/foodgram-backend
    restart: always
    volumes:
      - static_backend_value:/code/static_backend/
      - media_data:/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    image: ganetzckayaliza/foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend


  nginx:
    image: ganetzckayaliza/foodgram-nginx  
    # image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_backend_value:/var/html/static_backend/
      - media_data:/var/html/media/
    restart: always
    depends_on:
      - backend
      - frontend
